### ISSUE TITLE
I need some help.

### ISSUE THREAD

**Issue by fede-schwindt** [Tinh96nb/bot-telegram#1]
Guess i did something wrong :\
![Captura](https://user-images.githubusercontent.com/86686019/125674272-729fcc2b-bc3b-4cd6-bee4-97afcd886143.PNG)

**Comment by Tinh96nb** [comment]
sorry, i fixed it and ran ```yarn migrate``` command to initialize db before start.

**Comment by fede-schwindt** [comment]
> sorry, i fixed it and ran `yarn migrate` command to initialize db before start.

Thanks mate!
